# Build settings
markdown: kramdown
highlighter: rouge

# Site settings
title: "Predictions: The History of the Future"
description: > # this means to ignore newlines until "email:"
   A Contrafabulists Production

email: info@contrafabulists.com
#blog logo
logo: "/assets/images/cog.jpg"
logo2: "/assets/images/cog_tr.png"
# blog cover
cover: "/assets/images/owl.jpg"
covercredits: "http://bryanmmathers.com"

name: 'Contrafabulists'
author: 'Audrey Watters'
author_image: "/assets/images/author_aw.jpg"
author2: 'Kin Lane'
author_image2: "/assets/images/author_kl.jpg"

paginate:	5
paginate_path: "/blog/page:num"
permalink: /:categories/:year/:month/:day/:title 

url: "http://predictions.contrafabulists.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@contrafabulists' 

# social icons and sharing options
social:
  - icon:   twitter
    url:    https://twitter.com/contrafabulists
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&url="

  - icon:   facebook
    url: https://facebook.com/contrafabulists  
    desc: Like me on facebook
    share_url: http://www.facebook.com/sharer/sharer.php
    share_title: ?title=
    share_link: "?u="

  - icon:   github
    url:    https://github.com/Contrafabulists/predictions
    desc:   Fork me on github
    share_url: 
    share_title:
    share_link:

 # - icon:  google-plus
 #   url:   
 #   desc:  
 #   share_url:
 #   share_title:
 #   share_link:

  - icon: rss
    url:  http://predictions.contrafabulists.com/feed.xml
    desc: Subscribe
    share_url:
    share_title:
    share_link:

  - icon: envelope
    url:  mailto:info@contrafabulists.com
    desc: Email
    share_url:
    share_title:
    share_link:    
  

